import * as path from 'path';
import * as fs from 'fs';
import { AnalysisResult } from './analyzer/types';

/**
 * Auto-generates .agents/memory/ folder from analysis data.
 * Called after every CodeAtlas: Analyze Project.
 * 
 * Regenerated files: system-map.md, modules.json, feature-flows.json, conventions.md
 * Preserved files: business-rules.json, change-log.json (only created if not exists)
 */
export function generateMemory(workspaceRoot: string, analysis: AnalysisResult): void {
  const memoryDir = path.join(workspaceRoot, '.agents', 'memory');

  try {
    fs.mkdirSync(memoryDir, { recursive: true });
  } catch {
    console.error('CodeAtlas: Failed to create .agents/memory/ directory');
    return;
  }

  const nodes = analysis.graph.nodes;
  const links = analysis.graph.links;
  const nodeMap = new Map(nodes.map((n: any) => [n.id, n]));
  const nodeNameMap = new Map(nodes.map((n: any) => [n.id, n.label]));

  const modules = nodes.filter((n: any) => n.type === 'module' && n.filePath);
  const classes = nodes.filter((n: any) => n.type === 'class');
  const functions = nodes.filter((n: any) => n.type === 'function');
  const variables = nodes.filter((n: any) => n.type === 'variable');

  const stats = {
    modules: modules.length,
    classes: classes.length,
    functions: functions.length,
    variables: variables.length,
    dependencies: links.filter((l: any) => l.type === 'import').length,
    circularDeps: 0, // simplified
  };

  // === 1. system-map.md (always regenerate) ===
  const moduleLinks = links.filter((l: any) => {
    const src = nodeMap.get(l.source);
    const tgt = nodeMap.get(l.target);
    return src?.type === 'module' && tgt?.type === 'module' && src.filePath && tgt.filePath && l.type === 'import';
  });

  // Deduplicate module links
  const mlSet = new Set<string>();
  const dedupModuleLinks = moduleLinks.filter((l: any) => {
    const key = `${l.source}|${l.target}`;
    if (mlSet.has(key)) return false;
    mlSet.add(key);
    return true;
  });

  const topModules = modules.slice(0, 50);
  const topModuleIds = new Set(topModules.map((m: any) => m.id));
  const topModuleLinks = dedupModuleLinks.filter((l: any) => topModuleIds.has(l.source) && topModuleIds.has(l.target));

  const mermaidLines = ['```mermaid', 'graph TD'];
  let nodeCounter = 0;
  const mermaidIdMap = new Map<string, string>();
  for (const mod of topModules) {
    const mid = `m${nodeCounter++}`;
    mermaidIdMap.set(mod.id, mid);
    mermaidLines.push(`    ${mid}["📄 ${mod.label}"]`);
  }
  for (const link of topModuleLinks) {
    const s = mermaidIdMap.get(link.source);
    const t = mermaidIdMap.get(link.target);
    if (s && t) mermaidLines.push(`    ${s} -->|imports| ${t}`);
  }
  mermaidLines.push('```');

  // Count connections per module
  const moduleConnections = new Map<string, number>();
  for (const link of links) {
    if (link.type === 'import') {
      moduleConnections.set(link.source, (moduleConnections.get(link.source) || 0) + 1);
      moduleConnections.set(link.target, (moduleConnections.get(link.target) || 0) + 1);
    }
  }

  const keyModules = modules
    .map((m: any) => ({ name: m.label, path: m.filePath, connections: moduleConnections.get(m.id) || 0 }))
    .sort((a: any, b: any) => b.connections - a.connections)
    .slice(0, 20);

  const keyModulesSection = keyModules
    .map((m: any, i: number) => `${i + 1}. **${m.name}** (${m.connections} connections) — \`${path.relative(workspaceRoot, m.path || '')}\``)
    .join('\n');

  const systemMapContent = [
    `# System Map — ${path.basename(workspaceRoot)}`,
    `> Auto-generated by CodeAtlas on ${new Date().toISOString()}`,
    `> **DO NOT EDIT MANUALLY** — This file is regenerated on every analysis`,
    '',
    `## Overview`,
    `- **Modules**: ${stats.modules}`,
    `- **Functions**: ${stats.functions}`,
    `- **Classes**: ${stats.classes}`,
    `- **Dependencies**: ${stats.dependencies}`,
    '',
    `## Module Dependency Graph`,
    ...mermaidLines,
    '',
    `## Key Modules (by connection count)`,
    keyModulesSection,
  ].join('\n');

  fs.writeFileSync(path.join(memoryDir, 'system-map.md'), systemMapContent + '\n');

  // === 2. modules.json (always regenerate) ===
  const modulesJson = modules.map((m: any) => {
    const contained = links
      .filter((l: any) => l.source === m.id && l.type === 'contains')
      .map((l: any) => {
        const target = nodeMap.get(l.target);
        return target ? { name: target.label, type: target.type } : null;
      })
      .filter(Boolean);

    const imports = links
      .filter((l: any) => l.source === m.id && l.type === 'import')
      .map((l: any) => nodeNameMap.get(l.target) || l.target);

    return {
      name: m.label,
      path: m.filePath ? path.relative(workspaceRoot, m.filePath) : null,
      contains: contained,
      imports: imports,
      connectionCount: moduleConnections.get(m.id) || 0,
    };
  });

  fs.writeFileSync(path.join(memoryDir, 'modules.json'), JSON.stringify(modulesJson, null, 2));

  // === 3. feature-flows.json (always regenerate) ===
  const featureMap = new Map<string, string[]>();
  for (const mod of modules) {
    if (!mod.filePath) continue;
    const rel = path.relative(workspaceRoot, mod.filePath);
    const dir = path.dirname(rel).split(path.sep)[0] || '.';
    if (!featureMap.has(dir)) featureMap.set(dir, []);
    featureMap.get(dir)!.push(rel);
  }

  const featureFlows: Record<string, { files: string[]; entryPoints: string[] }> = {};
  for (const [dir, files] of featureMap) {
    const entryPoints = files
      .map((f: string) => {
        const moduleId = `module:${f.replace(/\\/g, '/')}`;
        const outgoing = links.filter((l: any) => l.source === moduleId && l.type === 'import').length;
        return { file: f, outgoing };
      })
      .sort((a: any, b: any) => b.outgoing - a.outgoing)
      .slice(0, 3)
      .map((e: any) => e.file);

    featureFlows[dir] = { files, entryPoints };
  }

  fs.writeFileSync(path.join(memoryDir, 'feature-flows.json'), JSON.stringify(featureFlows, null, 2));

  // === 4. business-rules.json (preserve — only create if not exists) ===
  const businessRulesPath = path.join(memoryDir, 'business-rules.json');
  if (!fs.existsSync(businessRulesPath)) {
    fs.writeFileSync(businessRulesPath, JSON.stringify([], null, 2));
  }

  // === 5. change-log.json (preserve — only create if not exists) ===
  const changeLogPath = path.join(memoryDir, 'change-log.json');
  if (!fs.existsSync(changeLogPath)) {
    fs.writeFileSync(changeLogPath, JSON.stringify([
      { timestamp: new Date().toISOString(), description: 'Initial analysis by CodeAtlas extension' }
    ], null, 2));
  }

  // === 6. conventions.md (always regenerate — auto-detected) ===
  const langs = new Map<string, number>();
  modules.forEach((m: any) => {
    if (!m.filePath) return;
    const ext = path.extname(m.filePath);
    langs.set(ext, (langs.get(ext) || 0) + 1);
  });

  const topLangs = Array.from(langs.entries()).sort((a, b) => b[1] - a[1]).slice(0, 5);
  const dirs = Array.from(featureMap.keys()).sort();

  const patterns: string[] = [];
  if (modules.some((m: any) => m.filePath?.includes('controller') || m.filePath?.includes('Controller'))) {
    patterns.push('- ✅ MVC Pattern (Controllers detected)');
  }
  if (modules.some((m: any) => m.filePath?.includes('service') || m.filePath?.includes('Service'))) {
    patterns.push('- ✅ Service Layer (Services detected)');
  }
  if (modules.some((m: any) => m.filePath?.includes('model') || m.filePath?.includes('Model'))) {
    patterns.push('- ✅ Model Layer (Models detected)');
  }
  if (modules.some((m: any) => m.filePath?.includes('middleware') || m.filePath?.includes('Middleware'))) {
    patterns.push('- ✅ Middleware Pattern');
  }
  if (modules.some((m: any) => m.filePath?.includes('test') || m.filePath?.includes('spec'))) {
    patterns.push('- ✅ Test Suite Present');
  }

  const conventionsContent = [
    `# Conventions — ${path.basename(workspaceRoot)}`,
    `> Auto-generated by CodeAtlas on ${new Date().toISOString()}`,
    `> **DO NOT EDIT MANUALLY** — This file is regenerated on every analysis`,
    '',
    `## Languages`,
    ...topLangs.map(([ext, count]) => `- \`${ext}\`: ${count} files`),
    '',
    `## Project Structure`,
    ...dirs.map((d) => `- \`${d}/\` — ${featureMap.get(d)?.length || 0} files`),
    '',
    `## Architecture Patterns Detected`,
    ...(patterns.length > 0 ? patterns : ['- No common patterns detected']),
  ].join('\n');

  fs.writeFileSync(path.join(memoryDir, 'conventions.md'), conventionsContent);

  // === 7. Auto-generate .agents/rules/ (only if not exists) ===
  generateRules(workspaceRoot);

  console.log(`CodeAtlas: Memory & rules synced to ${path.join(workspaceRoot, '.agents')}`);
}

/**
 * Auto-generates .agents/rules/ with CodeAtlas MCP instructions.
 * Only creates files if they don't already exist (preserves user customizations).
 */
function generateRules(workspaceRoot: string): void {
  const rulesDir = path.join(workspaceRoot, '.agents', 'rules');

  try {
    fs.mkdirSync(rulesDir, { recursive: true });
  } catch {
    console.error('CodeAtlas: Failed to create .agents/rules/ directory');
    return;
  }

  // === codeatlas-mcp.md — Tells AI how to use CodeAtlas MCP tools ===
  const mcpRulePath = path.join(rulesDir, 'codeatlas-mcp.md');
  if (!fs.existsSync(mcpRulePath)) {
    const mcpRule = `---
trigger: always_on
---

## CodeAtlas MCP — Codebase Intelligence

An MCP server named \`codeatlas\` is available. It provides code analysis data including project structure, dependencies, and code insights.

**Always use CodeAtlas MCP tools BEFORE manual file searches — faster and gives relationship context.**

### Workflow

1. **Before making changes** → call \`trace_feature_flow\` with a keyword to find related files
2. **Looking for a function/class** → call \`search_entities\` (faster than grep, includes relationships)
3. **Understanding connections** → call \`get_dependencies\` for import/call relationships
4. **High-level overview** → call \`generate_system_flow\` for Mermaid architecture diagram
5. **Execution flow of a feature** → call \`generate_feature_flow_diagram\` for call-chain Mermaid diagram
6. **Exploring a file** → call \`get_file_entities\` to see all entities in that file
7. **After making changes** → call \`sync_system_memory\` to update AI memory

### Available Tools

| Tool | When to use |
|------|-------------|
| \`list_projects\` | List all analyzed projects |
| \`get_project_structure\` | Overview of modules, classes, functions |
| \`get_dependencies\` | Import/call/containment relationships |
| \`get_insights\` | AI-generated code quality analysis |
| \`search_entities\` | Find function, class, or module by name |
| \`get_file_entities\` | All entities inside a specific file |
| \`generate_system_flow\` | Mermaid diagram of system architecture (module imports) |
| \`generate_feature_flow_diagram\` | Mermaid diagram of feature execution flow (call chains) |
| \`sync_system_memory\` | Update .agents/memory/ after code changes |
| \`trace_feature_flow\` | Trace feature flow before working on it |

### Setup

If CodeAtlas MCP is not configured, add it:

**Gemini / Antigravity** — \`.gemini/settings.json\`:
\`\`\`json
{
  "mcpServers": {
    "codeatlas": {
      "command": "npx",
      "args": ["-y", "@giauphan/codeatlas-mcp"]
    }
  }
}
\`\`\`

**Cursor** — \`.cursor/mcp.json\`:
\`\`\`json
{
  "mcpServers": {
    "codeatlas": {
      "command": "npx",
      "args": ["-y", "@giauphan/codeatlas-mcp"]
    }
  }
}
\`\`\`

**Claude Code CLI**:
\`\`\`bash
claude mcp add codeatlas -- npx -y @giauphan/codeatlas-mcp
\`\`\`

### Important
- Data comes from \`.codeatlas/analysis.json\` — run \`CodeAtlas: Analyze Project\` in the editor to generate
- If no data found, tell user to run the analysis command first
`;
    fs.writeFileSync(mcpRulePath, mcpRule);
  }

  // === auto-memory.md — Tells AI to read/sync memory automatically ===
  const memoryRulePath = path.join(rulesDir, 'auto-memory.md');
  if (!fs.existsSync(memoryRulePath)) {
    const memoryRule = `---
trigger: always_on
---

## AI System Memory — Auto-Read & Auto-Sync

### 🧠 MANDATORY: Read Memory at Start

**At the start of EVERY conversation**, before doing any work:

1. Check if \`.agents/memory/\` folder exists in the project
2. If it exists, read these files IN ORDER:
   - \`.agents/memory/system-map.md\` — Understand the system architecture
   - \`.agents/memory/business-rules.json\` — Know the business rules
   - \`.agents/memory/conventions.md\` — Know the coding conventions
   - \`.agents/memory/change-log.json\` — Know what changed recently
3. Use this context to avoid breaking existing logic

### 🔎 MANDATORY: Use CodeAtlas MCP to Understand Code BEFORE Making Changes

**NEVER start coding without understanding the codebase first.** Follow this flow:

1. **User describes a problem/feature** → FIRST call \`trace_feature_flow\` with a keyword
   - Returns the list of related files in \`readingOrder\`
   - Read those files to understand the current implementation

2. **Need to find a specific function/class** → call \`search_entities\` instead of grep
   - Faster and includes relationship data (who calls it, who imports it)

3. **Need to understand how things connect** → call \`get_dependencies\`
   - Shows import/call/containment relationships between modules

4. **Need a high-level overview** → call \`generate_system_flow\`
   - Returns a Mermaid diagram showing the full system architecture

5. **Need to see execution flow of a feature** → call \`generate_feature_flow_diagram\`
   - Returns a Mermaid flowchart or sequence diagram showing the call chain
   - Shows: entry point → controller → service → model step-by-step

6. **Need to know what's in a specific file** → call \`get_file_entities\`
   - Returns all classes, functions, variables in that file

**Example flow when user says "fix login timeout":**
\`\`\`
1. trace_feature_flow(keyword: "login")     → get list of related files
2. generate_feature_flow_diagram(keyword: "login") → see execution flow
3. Read files in readingOrder               → understand current logic
4. Fix the code                             → make changes
5. sync_system_memory(changeDescription: "Fixed login timeout") → update memory
\`\`\`

### 🔄 MANDATORY: Sync Memory After Changes

**After completing ANY code changes, you MUST call \`sync_system_memory\`:**

1. **\`changeDescription\`** (ALWAYS required): What you just changed
   - Example: \`"Fixed login timeout by adding retry logic"\`

2. **\`businessRule\`** (if user mentions domain logic):
   - Business rules are statements like:
     - "VIP users skip email verification"
     - "Only process videos with 1000+ likes"
     - "Free tier limited to 5 projects"
   - If user mentions any such rule, SAVE IT

**DO NOT SKIP THIS STEP.** If you forget to sync, the next conversation loses all context.

### Available Memory Tools

| Tool | When to use |
|------|-------------|
| \`generate_system_flow\` | See/understand system architecture (module imports) |
| \`generate_feature_flow_diagram\` | See execution flow of a feature (call chains) |
| \`sync_system_memory\` | After code changes (ALWAYS call this) |
| \`trace_feature_flow\` | Before working on a feature (understand context) |
| \`get_project_structure\` | Detailed entity listing |
| \`get_dependencies\` | Specific dependency relationships |
| \`search_entities\` | Find function/class by name |
| \`get_file_entities\` | Contents of a specific file |
| \`get_insights\` | Code quality / architecture analysis |
`;
    fs.writeFileSync(memoryRulePath, memoryRule);
  }

  // === IDE-specific rule files ===
  generateIDERules(workspaceRoot);
}

/**
 * Auto-generates IDE-specific rule files for Cursor, Claude Code, and Windsurf.
 * Only creates files if they don't already exist (preserves user customizations).
 */
function generateIDERules(workspaceRoot: string): void {
  const codeatlasRule = `# CodeAtlas MCP — Codebase Intelligence

An MCP server named \`codeatlas\` is available. It provides code analysis data including project structure, dependencies, and code insights.

**Always use CodeAtlas MCP tools BEFORE manual file searches — faster and gives relationship context.**

## Workflow

1. **Before making changes** → call \`trace_feature_flow\` with a keyword to find related files
2. **Looking for a function/class** → call \`search_entities\` (faster than grep, includes relationships)
3. **Understanding connections** → call \`get_dependencies\` for import/call relationships
4. **High-level overview** → call \`generate_system_flow\` for Mermaid architecture diagram
5. **Execution flow of a feature** → call \`generate_feature_flow_diagram\` for call-chain Mermaid diagram
6. **Exploring a file** → call \`get_file_entities\` to see all entities in that file
7. **After making changes** → call \`sync_system_memory\` to update AI memory

## Available Tools

| Tool | When to use |
|------|-------------|
| \`list_projects\` | List all analyzed projects |
| \`get_project_structure\` | Overview of modules, classes, functions |
| \`get_dependencies\` | Import/call/containment relationships |
| \`get_insights\` | AI-generated code quality analysis |
| \`search_entities\` | Find function, class, or module by name |
| \`get_file_entities\` | All entities inside a specific file |
| \`generate_system_flow\` | Mermaid diagram of system architecture (module imports) |
| \`generate_feature_flow_diagram\` | Mermaid diagram of feature execution flow (call chains) |
| \`sync_system_memory\` | Update .agents/memory/ after code changes |
| \`trace_feature_flow\` | Trace feature flow before working on it |

## Memory System

At the **start of EVERY conversation**, read \`.agents/memory/\` if it exists:
1. \`.agents/memory/system-map.md\` — System architecture
2. \`.agents/memory/business-rules.json\` — Business rules
3. \`.agents/memory/conventions.md\` — Coding conventions
4. \`.agents/memory/change-log.json\` — Recent changes

**After code changes**, ALWAYS call \`sync_system_memory(changeDescription: "what you changed")\`.
`;

  // === Cursor: .cursor/rules/codeatlas.mdc ===
  const cursorDir = path.join(workspaceRoot, '.cursor', 'rules');
  const cursorRulePath = path.join(cursorDir, 'codeatlas.mdc');
  if (!fs.existsSync(cursorRulePath)) {
    try {
      fs.mkdirSync(cursorDir, { recursive: true });
      const cursorRule = `---
description: CodeAtlas MCP Integration — Auto-read memory, use MCP tools before coding, sync after changes
globs:
alwaysApply: true
---

${codeatlasRule}

## Setup

Add to \`.cursor/mcp.json\`:
\`\`\`json
{
  "mcpServers": {
    "codeatlas": {
      "command": "npx",
      "args": ["-y", "@giauphan/codeatlas-mcp"]
    }
  }
}
\`\`\`
`;
      fs.writeFileSync(cursorRulePath, cursorRule);
      console.log('CodeAtlas: Generated .cursor/rules/codeatlas.mdc');
    } catch {
      // Cursor not in use, skip silently
    }
  }

  // === Claude Code: CLAUDE.md ===
  const claudeRulePath = path.join(workspaceRoot, 'CLAUDE.md');
  if (!fs.existsSync(claudeRulePath)) {
    try {
      const claudeRule = `${codeatlasRule}
## Setup

\`\`\`bash
claude mcp add codeatlas -- npx -y @giauphan/codeatlas-mcp
\`\`\`
`;
      fs.writeFileSync(claudeRulePath, claudeRule);
      console.log('CodeAtlas: Generated CLAUDE.md');
    } catch {
      // Skip silently
    }
  }

  // === Windsurf: .windsurfrules ===
  const windsurfRulePath = path.join(workspaceRoot, '.windsurfrules');
  if (!fs.existsSync(windsurfRulePath)) {
    try {
      fs.writeFileSync(windsurfRulePath, codeatlasRule);
      console.log('CodeAtlas: Generated .windsurfrules');
    } catch {
      // Skip silently
    }
  }
}
