import * as path from 'path';
import * as fs from 'fs';
import { AnalysisResult } from './analyzer/types';

/**
 * Auto-generates .agents/memory/ folder from analysis data.
 * Called after every CodeAtlas: Analyze Project.
 * 
 * Regenerated files: system-map.md, modules.json, feature-flows.json, conventions.md
 * Preserved files: business-rules.json, change-log.json (only created if not exists)
 */
export function generateMemory(workspaceRoot: string, analysis: AnalysisResult): void {
  const memoryDir = path.join(workspaceRoot, '.agents', 'memory');

  try {
    fs.mkdirSync(memoryDir, { recursive: true });
  } catch {
    console.error('CodeAtlas: Failed to create .agents/memory/ directory');
    return;
  }

  const nodes = analysis.graph.nodes;
  const links = analysis.graph.links;
  const nodeMap = new Map(nodes.map((n: any) => [n.id, n]));
  const nodeNameMap = new Map(nodes.map((n: any) => [n.id, n.label]));

  const modules = nodes.filter((n: any) => n.type === 'module' && n.filePath);
  const classes = nodes.filter((n: any) => n.type === 'class');
  const functions = nodes.filter((n: any) => n.type === 'function');
  const variables = nodes.filter((n: any) => n.type === 'variable');

  const stats = {
    modules: modules.length,
    classes: classes.length,
    functions: functions.length,
    variables: variables.length,
    dependencies: links.filter((l: any) => l.type === 'import').length,
    circularDeps: 0, // simplified
  };

  // === 1. system-map.md (always regenerate) ===
  const moduleLinks = links.filter((l: any) => {
    const src = nodeMap.get(l.source);
    const tgt = nodeMap.get(l.target);
    return src?.type === 'module' && tgt?.type === 'module' && src.filePath && tgt.filePath && l.type === 'import';
  });

  // Deduplicate module links
  const mlSet = new Set<string>();
  const dedupModuleLinks = moduleLinks.filter((l: any) => {
    const key = `${l.source}|${l.target}`;
    if (mlSet.has(key)) return false;
    mlSet.add(key);
    return true;
  });

  const topModules = modules.slice(0, 50);
  const topModuleIds = new Set(topModules.map((m: any) => m.id));
  const topModuleLinks = dedupModuleLinks.filter((l: any) => topModuleIds.has(l.source) && topModuleIds.has(l.target));

  const mermaidLines = ['```mermaid', 'graph TD'];
  let nodeCounter = 0;
  const mermaidIdMap = new Map<string, string>();
  for (const mod of topModules) {
    const mid = `m${nodeCounter++}`;
    mermaidIdMap.set(mod.id, mid);
    mermaidLines.push(`    ${mid}["📄 ${mod.label}"]`);
  }
  for (const link of topModuleLinks) {
    const s = mermaidIdMap.get(link.source);
    const t = mermaidIdMap.get(link.target);
    if (s && t) mermaidLines.push(`    ${s} -->|imports| ${t}`);
  }
  mermaidLines.push('```');

  // Count connections per module
  const moduleConnections = new Map<string, number>();
  for (const link of links) {
    if (link.type === 'import') {
      moduleConnections.set(link.source, (moduleConnections.get(link.source) || 0) + 1);
      moduleConnections.set(link.target, (moduleConnections.get(link.target) || 0) + 1);
    }
  }

  const keyModules = modules
    .map((m: any) => ({ name: m.label, path: m.filePath, connections: moduleConnections.get(m.id) || 0 }))
    .sort((a: any, b: any) => b.connections - a.connections)
    .slice(0, 20);

  const keyModulesSection = keyModules
    .map((m: any, i: number) => `${i + 1}. **${m.name}** (${m.connections} connections) — \`${path.relative(workspaceRoot, m.path || '')}\``)
    .join('\n');

  const systemMapContent = [
    `# System Map — ${path.basename(workspaceRoot)}`,
    `> Auto-generated by CodeAtlas on ${new Date().toISOString()}`,
    `> **DO NOT EDIT MANUALLY** — This file is regenerated on every analysis`,
    '',
    `## Overview`,
    `- **Modules**: ${stats.modules}`,
    `- **Functions**: ${stats.functions}`,
    `- **Classes**: ${stats.classes}`,
    `- **Dependencies**: ${stats.dependencies}`,
    '',
    `## Module Dependency Graph`,
    ...mermaidLines,
    '',
    `## Key Modules (by connection count)`,
    keyModulesSection,
  ].join('\n');

  fs.writeFileSync(path.join(memoryDir, 'system-map.md'), systemMapContent + '\n');

  // === 2. modules.json (always regenerate) ===
  const modulesJson = modules.map((m: any) => {
    const contained = links
      .filter((l: any) => l.source === m.id && l.type === 'contains')
      .map((l: any) => {
        const target = nodeMap.get(l.target);
        return target ? { name: target.label, type: target.type } : null;
      })
      .filter(Boolean);

    const imports = links
      .filter((l: any) => l.source === m.id && l.type === 'import')
      .map((l: any) => nodeNameMap.get(l.target) || l.target);

    return {
      name: m.label,
      path: m.filePath ? path.relative(workspaceRoot, m.filePath) : null,
      contains: contained,
      imports: imports,
      connectionCount: moduleConnections.get(m.id) || 0,
    };
  });

  fs.writeFileSync(path.join(memoryDir, 'modules.json'), JSON.stringify(modulesJson, null, 2));

  // === 3. feature-flows.json (always regenerate) ===
  const featureMap = new Map<string, string[]>();
  for (const mod of modules) {
    if (!mod.filePath) continue;
    const rel = path.relative(workspaceRoot, mod.filePath);
    const dir = path.dirname(rel).split(path.sep)[0] || '.';
    if (!featureMap.has(dir)) featureMap.set(dir, []);
    featureMap.get(dir)!.push(rel);
  }

  const featureFlows: Record<string, { files: string[]; entryPoints: string[] }> = {};
  for (const [dir, files] of featureMap) {
    const entryPoints = files
      .map((f: string) => {
        const moduleId = `module:${f.replace(/\\/g, '/')}`;
        const outgoing = links.filter((l: any) => l.source === moduleId && l.type === 'import').length;
        return { file: f, outgoing };
      })
      .sort((a: any, b: any) => b.outgoing - a.outgoing)
      .slice(0, 3)
      .map((e: any) => e.file);

    featureFlows[dir] = { files, entryPoints };
  }

  fs.writeFileSync(path.join(memoryDir, 'feature-flows.json'), JSON.stringify(featureFlows, null, 2));

  // === 4. business-rules.json (preserve — only create if not exists) ===
  const businessRulesPath = path.join(memoryDir, 'business-rules.json');
  if (!fs.existsSync(businessRulesPath)) {
    fs.writeFileSync(businessRulesPath, JSON.stringify([], null, 2));
  }

  // === 5. change-log.json (preserve — only create if not exists) ===
  const changeLogPath = path.join(memoryDir, 'change-log.json');
  if (!fs.existsSync(changeLogPath)) {
    fs.writeFileSync(changeLogPath, JSON.stringify([
      { timestamp: new Date().toISOString(), description: 'Initial analysis by CodeAtlas extension' }
    ], null, 2));
  }

  // === 6. conventions.md (always regenerate — auto-detected) ===
  const langs = new Map<string, number>();
  modules.forEach((m: any) => {
    if (!m.filePath) return;
    const ext = path.extname(m.filePath);
    langs.set(ext, (langs.get(ext) || 0) + 1);
  });

  const topLangs = Array.from(langs.entries()).sort((a, b) => b[1] - a[1]).slice(0, 5);
  const dirs = Array.from(featureMap.keys()).sort();

  const patterns: string[] = [];
  if (modules.some((m: any) => m.filePath?.includes('controller') || m.filePath?.includes('Controller'))) {
    patterns.push('- ✅ MVC Pattern (Controllers detected)');
  }
  if (modules.some((m: any) => m.filePath?.includes('service') || m.filePath?.includes('Service'))) {
    patterns.push('- ✅ Service Layer (Services detected)');
  }
  if (modules.some((m: any) => m.filePath?.includes('model') || m.filePath?.includes('Model'))) {
    patterns.push('- ✅ Model Layer (Models detected)');
  }
  if (modules.some((m: any) => m.filePath?.includes('middleware') || m.filePath?.includes('Middleware'))) {
    patterns.push('- ✅ Middleware Pattern');
  }
  if (modules.some((m: any) => m.filePath?.includes('test') || m.filePath?.includes('spec'))) {
    patterns.push('- ✅ Test Suite Present');
  }

  const conventionsContent = [
    `# Conventions — ${path.basename(workspaceRoot)}`,
    `> Auto-generated by CodeAtlas on ${new Date().toISOString()}`,
    `> **DO NOT EDIT MANUALLY** — This file is regenerated on every analysis`,
    '',
    `## Languages`,
    ...topLangs.map(([ext, count]) => `- \`${ext}\`: ${count} files`),
    '',
    `## Project Structure`,
    ...dirs.map((d) => `- \`${d}/\` — ${featureMap.get(d)?.length || 0} files`),
    '',
    `## Architecture Patterns Detected`,
    ...(patterns.length > 0 ? patterns : ['- No common patterns detected']),
  ].join('\n');

  fs.writeFileSync(path.join(memoryDir, 'conventions.md'), conventionsContent);

  console.log(`CodeAtlas: Memory synced to ${memoryDir}`);
}
